plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '[0.7,)'
}

version = '1.20.1-2.8.3'
group = 'kakiku.pig2mod'

base {
    archivesName = 'pig2mod-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                'pig2mod' {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', 'pig2mod'
        }

        server {
            property 'forge.enabledGameTestNamespaces', 'pig2mod'
            args '--nogui'
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', 'pig2mod', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "mixins.pig2.refmap.json"
    config 'mixins.pig2.json'
}

dependencies {
    minecraft "net.minecraftforge:forge:1.20.1-47.3.0"

    // Mixin annotation processor - generates the refmap at compile time
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : 'pig2mod',
                'Specification-Vendor'    : 'Kakiku',
                'Specification-Version'   : '1',
                'Implementation-Title'    : 'Pig2_1.20.1',
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : 'Kakiku',
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : 'mixins.pig2.json'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
